### ISSUE TITLE
Still being updated?

### ISSUE THREAD

**Issue by 8BitYoda** [TMMania/Vault-Analyzer#21]
These filters are amazing, and wanted to say thank you. I was also curious if these are still being updated or if you've moved on to bigger and better things. Either way thank you :)

**Comment by TMMania** [comment]
Yes, I still watch and update all of this when necessary. The basic ideas of armor never change and since I leave meta (Recovery / Resilience ) in the hands of the user I don't have to update often.

**Comment by 8BitYoda** [comment]
Fair enough :)
